"""update discount_end_date to allow null

Revision ID: 17d4d91bad61
Revises: 2e2f2652eac7
Create Date: 2025-04-24 10:30:06.331530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17d4d91bad61'
down_revision: Union[str, None] = '2e2f2652eac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('discount', 'discount_end_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('discount', 'discount_end_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
