"""update key for all tables

Revision ID: 2e2f2652eac7
Revises: cd3111fc7227
Create Date: 2025-04-19 21:39:31.654053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e2f2652eac7'
down_revision: Union[str, None] = 'cd3111fc7227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'author_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_foreign_key(None, 'book', 'author', ['author_id'], ['id'])
    op.create_foreign_key(None, 'book', 'category', ['category_id'], ['id'])
    op.create_foreign_key(None, 'discount', 'book', ['book_id'], ['id'])
    op.create_foreign_key(None, 'orderitem', 'book', ['book_id'], ['id'])
    op.create_foreign_key(None, 'orderitem', 'order', ['order_id'], ['id'])
    op.alter_column('review', 'book_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_foreign_key(None, 'review', 'book', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.alter_column('review', 'book_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(None, 'orderitem', type_='foreignkey')
    op.drop_constraint(None, 'orderitem', type_='foreignkey')
    op.drop_constraint(None, 'discount', type_='foreignkey')
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.alter_column('book', 'author_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
