"""change book.book_cover_photo and user.disable

Revision ID: 5f5c8c2d0825
Revises: 0f801f6430fb
Create Date: 2025-04-16 13:13:40.841032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f5c8c2d0825'
down_revision: Union[str, None] = '0f801f6430fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=False))
    op.drop_column('user', 'disabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('disabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###
