"""empty message

Revision ID: 7eb42d008fee
Revises: 7f61b1af0b75
Create Date: 2025-04-17 10:28:40.284378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eb42d008fee'
down_revision: Union[str, None] = '7f61b1af0b75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('rating_star', sa.Integer(), nullable=False))
    op.drop_column('review', 'rating_start')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('rating_start', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('review', 'rating_star')
    # ### end Alembic commands ###
